"""Initial

Revision ID: 59fc5590d021
Revises: 
Create Date: 2021-03-17 20:34:48.711620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fc5590d021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='couriertype'), nullable=True),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('working_hours', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__couriers'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('delivery_hours', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('assign_time', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk__orders__courier_id__couriers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__orders'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###
